//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OXGame.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameID { get; set; }
        public System.DateTime GameDate { get; set; }
        public int GameStatusID { get; set; }
        public int GameDuration { get; set; }
        public string GameComment { get; set; }
        public string ClientIP { get; set; }
    }
}
